export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ADDTO_FAVOURITES_REQUEST = 'ADDTO_FAVOURITES_REQUEST';
export const ADDTO_FAVOURITES_SUCCESS = 'ADDTO_FAVOURITES_SUCCESS';
export const ADDTO_FAVOURITES_FAILURE = 'ADDTO_FAVOURITES_FAILURE';

export const REMOVE_FROM_FAVOURITES_REQUEST = 'REMOVE_FROM_FAVOURITES_REQUEST';
export const REMOVE_FROM_FAVOURITES_SUCCESS = 'REMOVE_FROM_FAVOURITES_SUCCESS';
export const REMOVE_FROM_FAVOURITES_FAILURE = 'REMOVE_FROM_FAVOURITES_FAILURE';

export const GET_FAVOURITES_REQUEST = 'GET_FAVOURITES_REQUEST';
export const GET_FAVOURITES_SUCCESS = 'GET_FAVOURITES_SUCCESS'
export const GET_FAVOURITES_FAILURE = 'GET_FAVOURITES_FAILURE'











